language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  pear install pear/PHP_CodeSniffer
  phpenv rehash

script:
  phpunit Test.php
  phpcs do-php-library.php

matrix:
  fast_finish: true
